{
'file':[
      'swissprot.csv',
      'DrugBank.xml'
   ],
'Vocabulary':[
      ['drugbank vocabulary.csv',drug,'ID']
      ['diseaseVOcabulary.csv','disease','ID']
   ],
'entities':[
   ['drug','DrugBank.xml','ID'],
   ['protein','swissprot.csv','Entry']
   ##['disease','disease.tsv','ID']
],
'relations':[
   ['drug',products','gene'],
   ['protein','Codified by','gene'],
   ['protein','Interacts with','protein']
   ]
}
#maybe change relation because i can find many with same name