 {
  'file':[
       'swissprot.csv',
       'drugbank vocabulary.csv'
     ],
 'entities': [
     'drug',
     'protein'
     ],
  'relations':[
    ['protein', 'Interacts withs', 'gene'],
    ['protein', 'Interacts with', protein']
      ]
}