{
'file':[
      'swissprot.csv',
      'DrugBank.xml'
   ],
'Vocabulary':[
      ['drugbank vocabulary.csv','drug','DrugBank ID']
   ],
'entities':[
   ['drug','DrugBank.xml','drugbank-id','synonyms'],
   ['protein','swissprot.tsv','Entry','synonyms']
],
'relations':[
   ['drug','targets','disease','polypeptide','id','actions'],
   ['protein','Codified by','gene'],
   ['protein','Interacts with','protein']
   ]
}
#maybe change relation because i can find many with same name

   ##['protein','swissprot.csv','Entry']